version: '3.4'

services:
  chatapi:
    hostname: chatapi
    image: chatapi
    container_name: chatapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app

